version: 2
updates:

  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Amsterdam"
    assignees:
      - "alcohol"
    open-pull-requests-limit: 10
