language: minimal

dist: bionic

addons:
  apt:
    sources:
    - docker-bionic
    packages:
    - docker-ce

git:
  depth: 10
  quiet: true

before_install:
- docker --version
- make --version

script:
- make -j --output-sync=line build
- echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
- make push
- docker logout
