name: Docker

on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         * * * * *
    - cron:  '0 8 * * 2'
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to hub.docker.com registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.tag }}/Dockerfile
          target: base
          pull: true
          push: true
          tags: alcohol/php:${{ matrix.tag }}

      - name: Build xdebug image
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.tag }}/Dockerfile
          target: xdebug
          pull: true
          push: true
          tags: alcohol/php:${{ matrix.tag }}-xdebug
