name: Docker

on:
  schedule:
    #         ┌───────────── minute (0 - 59)
    #         │ ┌───────────── hour (0 - 23)
    #         │ │ ┌───────────── day of the month (1 - 31)
    #         │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         │ │ │ │ │
    #         * * * * *
    - cron:  '0 8 * * 2'
  push:
    branches:
      - main

jobs:

  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    steps:
      - uses: actions/checkout@v3
      - name: Build container(s)
        run: |
          docker build --file ${{ matrix.tag }}/Dockerfile --pull --no-cache --target base --tag alcohol/php:${{ matrix.tag }} .
          docker build --file ${{ matrix.tag }}/Dockerfile --pull --no-cache --target xdebug --tag alcohol/php:${{ matrix.tag }}-xdebug .
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: github.ref == 'refs/heads/main'
      - name: Push container(s)
        run: |
          docker push alcohol/php:${{ matrix.tag }}
          docker push alcohol/php:${{ matrix.tag }}-xdebug
        if: github.ref == 'refs/heads/main'
